<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-57228a
Date:    2018-02-07 16:55:49
Version: v2.1.0
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-57228a",
    "email": {
        "to": "linmmill@umich.edu",
        "cc": "",
        "bcc": "",
        "subject": "Test WPG Submission Form",
        "template": "",
        "sendmail_from": "jquery.form@aol.com"
    },
    "admin": {
        "users": "admin:4390c",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "mailgun",
    "smtp": {
        "host": "smtp.aol.com",
        "user": "jquery.form@aol.com",
        "password": "MailerTest2016",
        "port": "587",
        "security": "tls"
    },
    "mailgun": {
        "domain": "mg.jquery-form.com",
        "apiKey": "key-1fee8dabcdf62e1b78ef1c57bf553d6d",
        "fromEmail": "mailgun@jquery-form.com",
        "fromName": "JQuery Form"
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "blue"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [
        {
            "disabled": false,
            "action": "toggleVisibility",
            "selector": "f11",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f10",
                    "condition": "==",
                    "value": "Custom Application"
                }
            ]
        },
        {
            "disabled": false,
            "action": "toggleVisibility",
            "selector": "f12",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f11",
                    "condition": "==",
                    "value": "Python 3.x"
                },
                {
                    "disabled": false,
                    "selector": "f11",
                    "condition": "==",
                    "value": "Python 2.x"
                },
                {
                    "disabled": false,
                    "selector": "f11",
                    "condition": "==",
                    "value": "Node.js"
                }
            ]
        },
        {
            "disabled": false,
            "action": "toggleVisibility",
            "selector": "f21",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f9",
                    "condition": "==",
                    "value": "No"
                }
            ]
        },
        {
            "disabled": false,
            "action": "toggleVisibility",
            "selector": "f22",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f10",
                    "condition": "==",
                    "value": "Managed Drupal Site"
                }
            ]
        },
        {
            "disabled": false,
            "action": "toggleVisibility",
            "selector": "f16",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f10",
                    "condition": "==",
                    "value": "Custom Application"
                },
                {
                    "disabled": false,
                    "selector": "f12",
                    "condition": "==",
                    "value": "No"
                }
            ]
        },
        {
            "disabled": false,
            "action": "toggleVisibility",
            "selector": "f23",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f10",
                    "condition": "==",
                    "value": "Custom Application"
                },
                {
                    "disabled": false,
                    "selector": "f12",
                    "condition": "==",
                    "value": "Yes"
                }
            ]
        },
        {
            "disabled": false,
            "action": "toggleVisibility",
            "selector": "f30",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f26",
                    "condition": "==",
                    "value": "Add new"
                }
            ]
        },
        {
            "disabled": false,
            "action": "toggleVisibility",
            "selector": "f32",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f9",
                    "condition": "==",
                    "value": "Yes"
                }
            ]
        },
        {
            "disabled": false,
            "action": "toggleVisibility",
            "selector": "f34",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f10",
                    "condition": "==",
                    "value": "Managed Drupal Site"
                },
                {
                    "disabled": false,
                    "selector": "f11",
                    "condition": "==",
                    "value": "LAMP (MySQL 5.5, PHP 5.4)"
                },
                {
                    "disabled": false,
                    "selector": "f11",
                    "condition": "==",
                    "value": "Python 3.x"
                },
                {
                    "disabled": false,
                    "selector": "f11",
                    "condition": "==",
                    "value": "Python 2.x"
                },
                {
                    "disabled": false,
                    "selector": "f11",
                    "condition": "==",
                    "value": "Node.js"
                }
            ]
        }
    ],
    "fields": [
        {
            "label": "Page Navigation",
            "field_type": "page_navigation",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "navigation": {
                    "style": "steps",
                    "showNumber": true,
                    "isButtonPrev": false,
                    "titles": [
                        {
                            "id": "f4",
                            "title": "Build your environment"
                        },
                        {
                            "id": "f8",
                            "title": "Describe your needs"
                        },
                        {
                            "id": "f0",
                            "title": "Complete your order"
                        }
                    ]
                }
            },
            "id": "f5",
            "cid": "c31"
        },
        {
            "label": "Before you begin: Is your site or application for a course project?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Yes",
                        "checked": false
                    },
                    {
                        "label": "No",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "col-1"
                },
                "description": "",
                "mainDescription": "Sites or applications that are for a course project are available at no cost. You will be asked to provide a valid U-M course code."
            },
            "id": "f9",
            "cid": "c59"
        },
        {
            "label": "Please enter your course code.",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false,
                    "responsive": true
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-book"
                },
                "validators": {
                    "alphanumeric": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    },
                    "pattern": {
                        "enabled": false
                    }
                },
                "placeholder": "For example: ARCH 201",
                "hidden": true,
                "description": "",
                "mainDescription": ""
            },
            "id": "f32",
            "cid": "c157"
        },
        {
            "label": "What do you need hosting for?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Managed Drupal Site",
                        "checked": false,
                        "value": "",
                        "image": ""
                    },
                    {
                        "label": "Custom Application",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "mainDescription": "Your selection will ensure that we configure the environment to be suited to your needs.",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "col-1"
                }
            },
            "id": "f10",
            "cid": "c67"
        },
        {
            "label": "What starter image would you like to use?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "LAMP (MySQL 5.5, PHP 5.4)",
                        "checked": false
                    },
                    {
                        "label": "Python 2.x",
                        "checked": false
                    },
                    {
                        "label": "Python 3.x",
                        "checked": false
                    },
                    {
                        "label": "Node.js",
                        "checked": null
                    }
                ],
                "presetJson": "",
                "mainDescription": "Explanation about this selection - dictates what image streams are added to your project. As a dev, you can change\/customize.",
                "style": {
                    "columns": "col-1"
                },
                "hidden": true,
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f11",
            "cid": "c72"
        },
        {
            "label": "Would you like to add a MySQL database?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Yes",
                        "checked": false
                    },
                    {
                        "label": "No",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "mainDescription": "This is available through MiDatabase at no extra cost. If you already have a MySQL database, select ?",
                "hidden": true
            },
            "id": "f12",
            "cid": "c77"
        },
        {
            "label": "Provide the location (URL) of your git repository.",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mainDescription": "",
                "hidden": true
            },
            "id": "f34",
            "cid": "c203"
        },
        {
            "label": "Build your environment",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "page": {
                    "title": "Build your environment",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                }
            },
            "id": "f4",
            "cid": "c26"
        },
        {
            "label": "What URL would you like to use for your site\/application?",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "rightText": "web.umich.edu"
                },
                "validators": {
                    "pattern": {
                        "enabled": false,
                        "val": ".umich.edu"
                    },
                    "required": {
                        "enabled": true
                    },
                    "maxlength": {
                        "enabled": true,
                        "val": "60",
                        "msg": "Please enter no more than 60 characters."
                    },
                    "alphanumeric": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": true
                    }
                },
                "mainDescription": "Once your site is provisioned, you may request a custom URL through the hostmaster or point an existing domain to your site.",
                "placeholder": "Enter custom sub-domain URL here"
            },
            "id": "f13",
            "cid": "c82"
        },
        {
            "label": "Does your site\/application collect, store, or use student education record (FERPA) data?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Yes",
                        "checked": false
                    },
                    {
                        "label": "No",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "mainDescription": "Currently, FERPA is the only sensitive data type that can be hosted through this service. For more information about other sensitive data types, see the Sensitive Data Guide: https:\/\/www.safecomputing.umich.edu\/dataguide\/",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f14",
            "cid": "c90"
        },
        {
            "label": "Does your site\/app need to be highly available?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Yes",
                        "checked": false
                    },
                    {
                        "label": "No",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "mainDescription": "Definition of highly available = 99.9% uptime, redundant, etc. Spin up new containers during periods of high traffic. Cost. If you select \"No,\" this means your site may go down during high traffic periods. You can always request to make your site highly available later and\/or increase your RAM after monitoring your site's performance.",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "description": ""
            },
            "id": "f15",
            "cid": "c95"
        },
        {
            "label": "Container Size (RAM)",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Recommended (LARGE\/ > 4 GB)",
                        "value": "",
                        "checked": false
                    },
                    {
                        "label": "Downgrade to MEDIUM\/4 GB",
                        "checked": false,
                        "value": ""
                    },
                    {
                        "label": "Downgrade to SMALL\/1 GB",
                        "checked": false,
                        "value": ""
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false,
                "addon": {
                    "leftText": ""
                },
                "mainDescription": "Based on the information you provided, we recommend a LARGE container, which provides more than 4 GB of memory (RAM).\n\nYou may change your selection below. You can always add or reduce later. Keep in mind that",
                "hidden": true
            },
            "cid": "c114",
            "id": "f23",
            "labelHide": false
        },
        {
            "label": "Container Size (RAM)",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Recommended (MEDIUM\/ 4 GB)",
                        "value": "",
                        "checked": false
                    },
                    {
                        "label": "Downgrade to SMALL\/1 GB",
                        "checked": false,
                        "value": ""
                    },
                    {
                        "label": "Upgrade to LARGE\/ >4 GB",
                        "checked": false,
                        "value": ""
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false,
                "addon": {
                    "leftText": ""
                },
                "mainDescription": "Based on the information you provided, we recommend a MEDIUM container, which provides up to 4 GB of memory (RAM).\n\nYou may change your selection below. You can always add or reduce later.",
                "hidden": true
            },
            "id": "f16",
            "cid": "c121",
            "labelHide": false
        },
        {
            "label": "Container Size (RAM)",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Recommended (SMALL\/ 1 GB)",
                        "value": "",
                        "checked": false
                    },
                    {
                        "label": "Upgrade to MEDIUM\/4 GB",
                        "checked": false,
                        "value": ""
                    },
                    {
                        "label": "Upgrade to LARGE\/ >4 GB",
                        "checked": false,
                        "value": ""
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false,
                "addon": {
                    "leftText": ""
                },
                "mainDescription": "Based on the information you provided, we recommend a SMALL container, which provides up to 1 GB of memory (RAM).\n\nYou may change your selection below. You can always add or reduce later.",
                "hidden": true
            },
            "cid": "c108",
            "id": "f22",
            "labelHide": false
        },
        {
            "label": "Describe your needs",
            "field_type": "page_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "page": {
                    "title": "Describe your needs",
                    "labelPrev": "< Back",
                    "labelNext": "Next",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}",
                    "disabled": false
                }
            },
            "id": "f8",
            "cid": "c50"
        },
        {
            "label": "Billing & Contact Information",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                }
            },
            "id": "f17",
            "cid": "c129"
        },
        {
            "label": "Submitter's Uniqname",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": "",
                "mainDescription": "This person will serve as the contact person for this request.",
                "addon": {
                    "rightText": "",
                    "leftIcon": "glyphicon glyphicon-user"
                },
                "placeholder": "Type your uniqname here"
            },
            "id": "f25",
            "cid": "c145"
        },
        {
            "label": "Account Owner",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Same as Submitter",
                        "checked": false
                    },
                    {
                        "label": "Add new",
                        "checked": null
                    }
                ],
                "presetJson": "",
                "mainDescription": "This person will serve as the primary administrator for the hosting account and will be responsible for maintaining the site.",
                "style": {
                    "columns": "col-1"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f26",
            "cid": "c151",
            "labelHide": false
        },
        {
            "label": "Account Owner Uniqname:",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": "",
                "addon": {
                    "leftText": "",
                    "leftIcon": "glyphicon glyphicon-user"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": true
            },
            "id": "f30",
            "cid": "c158"
        },
        {
            "label": "MCommunity Group",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-group"
                },
                "mainDescription": "Description about the purpose of the MCommunity Group.",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f29",
            "cid": "c182"
        },
        {
            "label": "Shortcode",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "max": {
                        "enabled": true,
                        "val": "999999",
                        "msg": "Please enter a valid six-digit short code without spaces."
                    },
                    "compareTo": {
                        "enabled": false,
                        "method": "<=",
                        "diff": "999999"
                    },
                    "min": {
                        "enabled": true,
                        "val": "111111",
                        "msg": "Please enter a valid six-digit short code without spaces."
                    }
                },
                "mainDescription": "Please enter the six-digit short code to which you'd like to bill this order.",
                "placeholder": "Enter six digit shortcode with no spaces",
                "hidden": true,
                "addon": {
                    "leftIcon": "glyphicon glyphicon-barcode"
                }
            },
            "id": "f21",
            "cid": "c158"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Complete your order",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class